#ifndef TREE_SITTER_RST_TOKENS_H_
#define TREE_SITTER_RST_TOKENS_H_

enum TokenType {
  // Whitespace
  T_NEWLINE,
  T_BLANKLINE,
  T_INDENT,
  T_NEWLINE_INDENT,
  T_DEDENT,

  // Sections
  T_OVERLINE,
  T_UNDERLINE,

  // Transitions
  T_TRANSITION,

  // Lists
  T_CHAR_BULLET,
  T_NUMERIC_BULLET,
  T_FIELD_MARK,
  T_FIELD_MARK_END,

  // Literal blocks
  T_LITERAL_INDENTED_BLOCK_MARK,
  T_LITERAL_QUOTED_BLOCK_MARK,
  T_QUOTED_LITERAL_BLOCK,

  // Line blocks
  T_LINE_BLOCK_MARK,

  // Block quotes
  T_ATTRIBUTION_MARK,

  // Doctest blocks
  T_DOCTEST_BLOCK_MARK,

  // Tables (flat nodes, scanner gobbles the whole table block)
  T_GRID_TABLE,
  T_SIMPLE_TABLE,

  // Inline markup
  T_TEXT,
  T_ESCAPE_SEQUENCE,
  T_EMPHASIS,
  T_STRONG,
  T_INTERPRETED_TEXT,
  T_INTERPRETED_TEXT_PREFIX,
  T_ROLE_NAME_PREFIX,
  T_ROLE_NAME_SUFFIX,
  T_LITERAL,
  // substitution_reference sub-tokens
  T_SUBSTITUTION_OPEN,
  T_SUBSTITUTION_NAME,
  T_SUBSTITUTION_CLOSE,
  // inline_target sub-tokens
  T_INLINE_TARGET_OPEN,
  T_INLINE_TARGET_NAME,
  T_INLINE_TARGET_CLOSE,
  // footnote_reference sub-tokens
  T_FOOTNOTE_REFERENCE_OPEN,
  T_FOOTNOTE_REFERENCE_LABEL,
  // citation_reference sub-tokens
  T_CITATION_REFERENCE_OPEN,
  T_CITATION_REFERENCE_LABEL,
  // shared close for footnote and citation references
  T_REFERENCE_LABEL_CLOSE,
  // bare reference sub-tokens
  T_REFERENCE_BARE_NAME,
  T_REFERENCE_BARE_MARK,
  T_REFERENCE_OPEN_BACKTICK,
  T_REFERENCE_NAME,
  T_EMBEDDED_URI,
  T_REFERENCE_END_MARK,
  T_STANDALONE_HYPERLINK,

  // Markup blocks
  T_EXPLICIT_MARKUP_START,
  T_FOOTNOTE_LABEL,
  T_CITATION_LABEL,
  T_TARGET_NAME,
  T_ANONYMOUS_TARGET_MARK,
  T_DIRECTIVE_NAME,
  T_SUBSTITUTION_MARK,
  T_EMPTY_COMMENT,

  T_INVALID_TOKEN,

  T_CLASSIFIER_INDENT_CHECK,
};

#endif /* TREE_SITTER_RST_TOKENS_H_ */
