#!/usr/bin/env python3

"""
Script to generate a C header file with all the punctuation characters used in reStructuredText.

Usage:
    python gen_punctuation_chars.py > punctuation_chars.h

Or call it from the makefile (recommended):

    make gen-punctuation-chars
"""

def is_ascii(ch) -> bool:
    return ord(ch) <= 127


def c_repr(ch) -> str:
    if is_ascii(ch):
        if ch == "'":
            return "'\\''"  # special case for single quote
        return repr(ch)
    return hex(ord(ch))


def unescape(chars: str) -> list[tuple[str, bool]]:
    """Resolve regex escapes in a docutils punctuation string.

    docutils exposes these strings as regex character-class fragments, so
    they contain escapes: ``\\\\`` is one literal backslash, ``\\-`` a
    literal dash (not a range sign), ``\\[`` a literal bracket. Returns
    ``(char, was_escaped)`` pairs.
    """
    pairs = []
    i = 0
    while i < len(chars):
        if chars[i] == "\\" and i + 1 < len(chars):
            pairs.append((chars[i + 1], True))
            i += 2
        else:
            pairs.append((chars[i], False))
            i += 1
    return pairs


def generate_c_chars_define(name: str, chars: str, expects_range=False) -> list[str]:
    INDENT = " " * 2
    pairs = unescape(chars)
    singles: list[str] = []
    ranges: list[tuple[str, str]] = []
    i = 0
    while i < len(pairs):
        ch, _ = pairs[i]
        # A non-ascii char followed by an unescaped '-' denotes an
        # inclusive range.
        if not is_ascii(ch) and i + 2 < len(pairs) and pairs[i + 1] == ("-", False):
            end, _ = pairs[i + 2]
            if is_ascii(end):
                raise Exception(f"Expected unicode, found ascii: {end}")
            ranges.append((ch, end))
            i += 3
            continue
        singles.append(ch)
        i += 1

    # docutils concatenates overlapping sets (e.g. quotes appear in both
    # closers and closing_delimiters), so drop duplicates while keeping
    # the original order.
    seen = set()
    singles = [ch for ch in singles if not (ch in seen or seen.add(ch))]

    c_chars = [f"const int32_t {name}[] = {{"]
    c_chars.extend(f"{INDENT}{c_repr(ch)}," for ch in singles)
    c_chars.append("};")

    c_char_ranges = [f"const int32_t {name}_range[][2] = {{"]
    c_char_ranges.extend(
        f"{INDENT}{{{c_repr(start)}, {c_repr(end)}}}," for start, end in ranges
    )
    c_char_ranges.append("};")

    if ranges:
        if not expects_range:
            raise Exception(f"Expected no ranges, but a range was found for {name}")
        return c_chars + c_char_ranges
    if expects_range:
        raise Exception(f"Expected ranges, but none found for {name}")
    return c_chars


def main():
    # Imported here so the pure string-processing helpers stay usable
    # (and testable) without docutils installed.
    from docutils.utils.punctuation_chars import (
        closers,
        closing_delimiters,
        delimiters,
        openers,
    )

    lines = [
        "// This file is generated by utils/gen_punctuation_chars.py, DO NOT EDIT.",
        "",
        "#ifndef TREE_SITTER_RST_PUNCTUATION_CHARS_H_",
        "#define TREE_SITTER_RST_PUNCTUATION_CHARS_H_",
        "",
    ]

    lines.extend(generate_c_chars_define("start_chars", openers, expects_range=False))
    lines.append("")

    lines.extend(generate_c_chars_define("delim_chars", delimiters, expects_range=True))
    lines.append("")

    lines.extend(
        generate_c_chars_define("end_chars", closing_delimiters + closers, expects_range=False)
    )
    lines.append("")

    lines.append("#endif /* ifndef TREE_SITTER_RST_PUNCTUATION_CHARS_H_ */")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
